Fix missing dependency - ajv is needed in runtime, not just dev
    $ ./node_modules/.bin/jschemer --help
    node:internal/modules/cjs/loader:1080
      throw err;
      ^

    Error: Cannot find module 'ajv'
    Require stack:
    - node_modules/jschemer/lib/build/getSchemas.js
    - node_modules/jschemer/lib/build/index.js
    - node_modules/jschemer/lib/jschemer.js
    - node_modules/jschemer/index.js